apiVersion: apps/v1
kind: Deployment
metadata:
  name: network
  labels:
    app: network
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
      - name: mme
        image: weronikag/stud:1.0.0
        ports:
        - containerPort: 80
      - name: upf
        image: ubuntu
        command: ["/bin/sleep",'3650d"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
