apiVersion: v1
kind: Pod
metadata:
  name: mme
  labels:
    app: mme
spec:
  containers:
    - name: mme
      image: weronikag/stud:1.0.0
      ports:
        - name: web
          containerPort: 80
          protocol: TCP