apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mme
  labels:
   app: mme
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  selector:
    app: mme
